language: cpp

sudo: false

compiler:
  - gcc

env:
  matrix:
    - COMPILER=g++-4.6 CCOMPILER=gcc-4.6
    - COMPILER=g++-4.7 CCOMPILER=gcc-4.7
    - COMPILER=g++-4.8 CCOMPILER=gcc-4.8
    - COMPILER=g++-4.9 CCOMPILER=gcc-4.9
    - COMPILER=g++-5 CCOMPILER=gcc-5
    - COMPILER=clang++-3.6 CCOMPILER=clang-3.6

matrix:
  allow_failures:
    - env: COMPILER=g++-4.6 CCOMPILER=gcc-4.6

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise
      - llvm-toolchain-precise-3.6
      - llvm-toolchain-precise-3.7
    packages:
      - g++-4.6
      - g++-4.7
      - g++-4.8
      - g++-4.9
      - g++-5
      - clang-3.6
      - valgrind
      - python-pip
      - python-yaml

before_script:
  - export CXX=$COMPILER CC=$CCOMPILER
  - cmake --version
  - mkdir build
  - cd build
  - cmake -LAH ..

script:
  - make VERBOSE=1
